language: android
sudo: false

android:
  components:
    - tools
    - build-tools-28.0.2
    - android-27
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

script:

  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew clean build
