language: android
sudo: required

jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - android-24
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

    # Emulator for the tests
    - sys-img-armeabi-v7a-android-24

script:

  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew clean build
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
